### ISSUE TITLE
About test case dataset

### ISSUE THREAD

**Issue by unicornt** [erxiaozhou/spec2tcs#1]
Hi, could you provide the test case dataset(the .wasm code) generated by `WADIFF`? We want to do the further experiments based on your dataset.
Thank you very much!

**Comment by erxiaozhou** [comment]
Hi,
As introduced in the paper, there are two kinds of test cases, i.e., test cases generated by the symbolic execution and test cases generated by the mutator.
1.  You can download the test cases generated by the symbolic execution by this [link](https://connectpolyu-my.sharepoint.com/:u:/g/personal/20036633r_connect_polyu_hk/EZlhfnvhsFNAnAl65eUAS2YBoocINXIm9DQSF4cVBPD23A?e=agtKv7). 
2. The test cases generated by the mutator exhibit a certain level of randomness, and furthermore. Therefore, I haven't organized this portion of test cases at the moment. This [list]( https://github.com/erxiaozhou/WaDiff/blob/main/material/issue_report_list.md) includes bug-triggering cases generated by WADIFF, and it also includes bug-triggering cases generated by the mutator.

In a few days, I will open-source all of the code along with the runtime being tested. At that point, you will be able to generate them on your own.
If you still have any questions, please feel free to reply to me, thank you.

**Comment by unicornt** [comment]
Thank you very much! Hope you a good weekend!
